# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_lifetime: 86400
        gc_maxlifetime: 7200  
        
    ## To fix Mercure Issue (?)
    http_client:
        default_options:
            verify_peer: false

    # http_cache:
    #     enabled: true
    #     trace_level: full
    #     trace_header: X-Symfony-Cache
    #     debug: true
    #esi: true
    #fragments: true
    
    # csrf_protection: false
    # form:
    #     csrf_protection:
    #         enabled: false

    router:
        default_uri: '%env(APP_URL)%'

# when@prod:
#     framework:
#         http_cache: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
