# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    image: app-php-prod
    environment:
      CADDY_EXTRA_CONFIG: |
        https:// {
          tls /etc/caddy/certs/tls.crt /etc/caddy/certs/tls.key
        }
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
      APP_ENV: prod
  

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8026:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
