apiVersion: batch/v1
kind: CronJob
metadata:
  name: blaze-competition-cronjob
  namespace: blaze-competition
spec:
  schedule: "*/1 * * * *" # Runs every minute (cron format)
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: 127.0.0.1:32000/app-php-prod:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
              # 2. Provide the loop as a multi-line argument
              args:
                - |
                  for i in 1 2 3; do
                    echo "--> Starting run $i of 3..."
                    php bin/console app:capture-competition-stats
                    echo "--> Run $i finished. Waiting 10 seconds..."
                    sleep 10
                  done
                  echo "--> All 3 runs complete."
              envFrom:
                - configMapRef:
                    name: blaze-competition-config # Pulls common environment variables
              env: # Override specific environment variables for cronjob
                - name: RUN_MIGRATIONS
                  value: "false"
              resources:
                limits:
                  memory: "256Mi"
                  cpu: "500m"
                requests:
                  memory: "32Mi"
                  cpu: "100m"
          restartPolicy: OnFailure