version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8099:8080" # Jenkins web UI
      - "50000:50000" # For JNLP-based agents
    volumes:
      - jenkins_data:/var/jenkins_home # Persists Jenkins data and configuration
      - /var/run/docker.sock:/var/run/docker.sock # Allows Jenkins to use the host's Docker daemon
      - ${HOME}/.kube/microk8s-config:/root/.kube/config:ro # Mounts MicroK8s config for kubectl 
    networks:
      - default

volumes:
  jenkins_data:

networks:
  default:
    name: jenkins_network