# k8s/keda-scaledobject-low-priority.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-low-priority-scaler
  namespace: blaze-competition-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messenger-worker-submission-low-priority # Target the specific low-priority worker
  pollingInterval: 30
  minReplicaCount: 0
  maxReplicaCount: 2
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://guest:guest@rabbitmq-service:5672/%2f
      queueName: submission_low_priority_queue
      queueLength: "200"