# k8s/scheduler-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-scheduler
  namespace: blaze-competition-dev
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scheduler
            image: 192.168.56.11:32000/blaze-competition/app:latest
            command: ["php", "bin/console", "scheduler:run", "--env=prod"]
            envFrom:
            - configMapRef: { name: app-config }
            volumeMounts:
            - name: app-code
              mountPath: /app
            - name: var-volume
              mountPath: /app/var
          restartPolicy: OnFailure
          volumes:
          - name: app-code
            emptyDir: {}
          - name: var-volume
            emptyDir: {}