apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-worker-submission-low-priority
  namespace: blaze-competition-dev
  labels:
    app: messenger-worker-submission-low-priority
spec:
  replicas: 0 # KEDA will manage the replica count, start at 0 or 1
  selector:
    matchLabels:
      app: messenger-worker-submission-low-priority
  template:
    metadata:
      labels:
        app: messenger-worker-submission-low-priority
    spec:
      containers:
      - name: worker
        image: 192.168.56.11:32000/blaze-competition/app:latest # Your FrankenPHP app image (contains CLI)
        command: ["php", "bin/console", "messenger:consume", "submission_amqp", "--queues=submission_low_priority_queue", "--verbose", "--time-limit=3600", "--memory-limit=128M"]
        envFrom:
        - configMapRef: { name: app-config }
        - secretRef: { name: app-secrets } # Still needed if you use secrets
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: var-volume
          mountPath: /app/var
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      volumes:
      - name: app-code
        emptyDir: {}
      - name: var-volume
        emptyDir: {}
      initContainers:
      - name: copy-code
        image: 192.168.56.11:32000/blaze-competition/app:latest
        command: ["sh", "-c", "cp -a /app/. /app_tmp && composer install --no-dev --optimize-autoloader --classmap-authoritative -d /app_tmp && cp -a /app_tmp/. /app"]
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: var-volume
          mountPath: /app_tmp/var