# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "vm-docker"
  config.vm.hostname = "vm-docker"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6192"
    vb.cpus = "6"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/^#DNS=.*/DNS=8.8.8.8 8.8.4.4/' /etc/systemd/resolved.conf
    sudo systemctl restart systemd-resolved
  SHELL
end
