apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: blaze-competition
  labels:
    app: blaze-competition-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  clusterIP: None # <-- Makes the service headless for the StatefulSet
  selector:
    app: blaze-competition-db
---
apiVersion: apps/v1
kind: StatefulSet # <-- Changed from Deployment
metadata:
  name: blaze-competition-db
  namespace: blaze-competition
  labels:
    app: blaze-competition-db
spec:
  serviceName: "database" # <-- Links to the headless service above
  replicas: 1
  selector:
    matchLabels:
      app: blaze-competition-db
  template:
    metadata:
      labels:
        app: blaze-competition-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: blaze-competition-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-data # <-- This name must match the template below
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command: ["/bin/bash", "-c", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/bash", "-c", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates: # <-- Automatically creates a PersistentVolumeClaim
  - metadata:
      name: database-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi